#

### Get data from tmdb

In [3]:
import pandas as pd
path = 'VI_CineView/Data'

def load_data(file):
    df = pd.read_csv(path +'/'+ file)
    return df

In [4]:
budgetDF = load_data("output.csv")#Data from boxOfficeMojo
budgetDF

,Rank,Title,Worldwide Lifetime Gross,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,Year
0,1,Avengers: Endgame,"$2,797,800,564","$858,373,000",30.7%,"$1,939,427,564",69.3%,2019
1,2,Avatar,"$2,789,968,301","$760,507,625",27.3%,"$2,029,460,676",72.7%,2009
2,3,Titanic,"$2,187,463,944","$659,363,944",30.1%,"$1,528,100,000",69.9%,1997
3,4,Star Wars: Episode VII - The Force Awakens,"$2,068,223,624","$936,662,225",45.3%,"$1,131,561,399",54.7%,2015
4,5,Avengers: Infinity War,"$2,048,359,754","$678,815,482",33.1%,"$1,369,544,272",66.9%,2018
5,6,Jurassic World,"$1,670,400,637","$652,270,625",39%,"$1,018,130,012",61%,2015
6,7,The Lion King,"$1,655,151,910","$543,491,835",32.8%,"$1,111,660,075",67.2%,2019
7,8,The Avengers,"$1,518,812,988","$623,357,910",41%,"$895,455,078",59%,2012
8,9,Furious Seven,"$1,515,047,671","$353,007,020",23.3%,"$1,162,040,651",76.7%,2015
9,10,Avengers: Age of Ultron,"$1,402,805,868","$459,005,868",32.7%,"$943,800,000",67.3%,2015
10,11,Black Panther,"$1,346,913,161","$700,059,566",52%,"$646,853,595",48%,2018
11,12,Harry Potter and the Deathly Hallows: Part 2,"$1,341,932,398","$381,409,310",28.4%,"$960,523,088",71.6%,2011
12,13,Star Wars: Episode VIII - The Last Jedi,"$1,332,539,889","$620,181,382",46.5%,"$712,358,507",53.5%,2017
13,14,Jurassic World: Fallen Kingdom,"$1,308,467,944","$417,719,760",31.9%,"$890,748,184",68.1%,2018
14,15,Frozen,"$1,274,219,009","$400,738,009",31.4%,"$873,481,000",68.6%,2013
15,16,Beauty and the Beast,"$1,263,521,126","$504,014,165",39.9%,"$759,506,961",60.1%,2017
16,17,Incredibles 2,"$1,242,805,359","$608,581,744",49%,"$634,223,615",51%,2018
17,18,The Fate of the Furious,"$1,236,005,118","$226,008,385",18.3%,"$1,009,996,733",81.7%,2017
18,19,Iron Man Three,"$1,214,811,252","$409,013,994",33.7%,"$805,797,258",66.3%,2013
19,20,Minions,"$1,159,398,397","$336,045,770",29%,"$823,352,627",71%,2015
20,21,Captain America: Civil War,"$1,153,296,293","$408,084,349",35.4%,"$745,211,944",64.6%,2016
21,22,Aquaman,"$1,148,161,807","$335,061,807",29.2%,"$813,100,000",70.8%,2018
22,23,Spider-Man: Far from Home,"$1,131,845,802","$390,532,085",34.5%,"$741,313,717",65.5%,2019
23,24,Captain Marvel,"$1,128,274,794","$426,829,839",37.8%,"$701,444,955",62.2%,2019
24,25,Transformers: Dark of the Moon,"$1,123,794,079","$352,390,543",31.4%,"$771,403,536",68.6%,2011
25,26,The Lord of the Rings: The Return of the King,"$1,120,424,614","$377,845,905",33.7%,"$742,578,709",66.3%,2003
26,27,Skyfall,"$1,108,561,013","$304,360,277",27.5%,"$804,200,736",72.5%,2012
27,28,Transformers: Age of Extinction,"$1,104,054,072","$245,439,076",22.2%,"$858,614,996",77.8%,2014
28,29,The Dark Knight Rises,"$1,081,041,287","$448,139,099",41.4%,"$632,902,188",58.6%,2012
29,30,Toy Story 4,"$1,073,166,397","$433,954,795",40.4%,"$639,211,602",59.6%,2019
...,...,...,...,...,...,...,...,...
170,171,Fifty Shades of Grey,"$569,651,467","$166,167,230",29.2%,"$403,484,237",70.8%,2015
171,172,Kong: Skull Island,"$566,652,812","$168,052,812",29.7%,"$398,600,000",70.3%,2017
172,173,The Smurfs,"$563,749,323","$142,614,158",25.3%,"$421,135,165",74.7%,2011
173,174,Cars 2,"$559,852,396","$191,452,396",34.2%,"$368,400,000",65.8%,2011
174,175,Puss in Boots,"$554,987,477","$149,260,504",26.9%,"$405,726,973",73.1%,2011
175,176,Mei ren yu,"$553,810,228","$3,232,685",0.6%,"$550,577,543",99.4%,2016
176,177,Armageddon,"$553,709,788","$201,578,182",36.4%,"$352,131,606",63.6%,1998
177,178,King Kong,"$550,517,357","$218,080,025",39.6%,"$332,437,332",60.4%,2005
178,179,Ted,"$549,368,315","$218,815,487",39.8%,"$330,552,828",60.2%,2012
179,180,Star Wars: Episode V - The Empire Strikes Back,"$547,879,454","$290,271,960",53%,"$257,607,494",47%,1980
180,181,American Sniper,"$547,426,372","$350,126,372",64%,"$197,300,000",36%,2014
181,182,Mission: Impossible II,"$546,388,105","$215,409,889",39.4%,"$330,978,216",60.6%,2000
182,183,Tang ren jie tan an 2,"$544,061,916","$1,983,984",0.4%,"$542,077,932",99.6%,2018
183,184,X-Men: Apocalypse,"$543,934,105","$155,442,489",28.6%,"$388,491,616",71.4%,2016
184,185,Sherlock Holmes: A Game of Shadows,"$543,848,418","$186,848,418",34.4%,"$357,000,000",65.6%,2011
185,186,Despicable Me,"$543,113,985","$251,513,985",46.3%,"$291,600,000",53.7%,2010
186,187,The Day After Tomorrow,"$542,771,772","$186,740,799",34.4%,"$356,030,973",65.6%,2004
187,188,Cinderella,"$542,351,353","$201,151,353",37.1%,"$341,200,000",62.9%,2015
188,189,Madagascar,"$542,063,846","$193,595,521",35.7%,"$348,468,325",64.3%,2005
189,190,World War Z,"$540,007,876","$202,359,711",37.5%,"$337,648,165",62.5%,2013
190,191,Brave,"$538,983,207","$237,283,207",44%,"$301,700,000",56%,2012
191,192,The Revenant,"$532,950,503","$183,637,894",34.5%,"$349,312,609",65.5%,2015
192,193,The Meg,"$530,243,742","$145,443,742",27.4%,"$384,800,000",72.6%,2018
193,194,Ralph Breaks the Internet,"$529,323,962","$201,091,711",38%,"$328,232,251",62%,2018
194,195,Hotel Transylvania 3: Summer Vacation,"$528,583,774","$167,510,016",31.7%,"$361,073,758",68.3%,2018
195,196,The Boss Baby,"$527,965,936","$175,003,033",33.2%,"$352,962,903",66.8%,2017
196,197,The Simpsons Movie,"$527,071,022","$183,135,014",34.8%,"$343,936,008",65.2%,2007
197,198,Dunkirk,"$526,940,665","$189,740,665",36%,"$337,200,000",64%,2017
198,199,Godzilla,"$524,976,069","$200,676,069",38.2%,"$324,300,000",61.8%,2014
199,200,Sherlock Holmes,"$524,028,679","$209,028,679",39.9%,"$315,000,000",60.1%,2009

In [49]:
budgetDF["Worldwide Lifetime Gross"] = budgetDF["Worldwide Lifetime Gross"].replace({'\$': '', ',': ''}, regex=True)
budgetDF

,Rank,Title,Worldwide Lifetime Gross,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,Year
0,1,Avengers: Endgame,2797800564,"$858,373,000",30.7%,"$1,939,427,564",69.3%,2019
1,2,Avatar,2789968301,"$760,507,625",27.3%,"$2,029,460,676",72.7%,2009
2,3,Titanic,2187463944,"$659,363,944",30.1%,"$1,528,100,000",69.9%,1997
3,4,Star Wars: Episode VII - The Force Awakens,2068223624,"$936,662,225",45.3%,"$1,131,561,399",54.7%,2015
4,5,Avengers: Infinity War,2048359754,"$678,815,482",33.1%,"$1,369,544,272",66.9%,2018
5,6,Jurassic World,1670400637,"$652,270,625",39%,"$1,018,130,012",61%,2015
6,7,The Lion King,1655151910,"$543,491,835",32.8%,"$1,111,660,075",67.2%,2019
7,8,The Avengers,1518812988,"$623,357,910",41%,"$895,455,078",59%,2012
8,9,Furious Seven,1515047671,"$353,007,020",23.3%,"$1,162,040,651",76.7%,2015
9,10,Avengers: Age of Ultron,1402805868,"$459,005,868",32.7%,"$943,800,000",67.3%,2015
10,11,Black Panther,1346913161,"$700,059,566",52%,"$646,853,595",48%,2018
11,12,Harry Potter and the Deathly Hallows: Part 2,1341932398,"$381,409,310",28.4%,"$960,523,088",71.6%,2011
12,13,Star Wars: Episode VIII - The Last Jedi,1332539889,"$620,181,382",46.5%,"$712,358,507",53.5%,2017
13,14,Jurassic World: Fallen Kingdom,1308467944,"$417,719,760",31.9%,"$890,748,184",68.1%,2018
14,15,Frozen,1274219009,"$400,738,009",31.4%,"$873,481,000",68.6%,2013
15,16,Beauty and the Beast,1263521126,"$504,014,165",39.9%,"$759,506,961",60.1%,2017
16,17,Incredibles 2,1242805359,"$608,581,744",49%,"$634,223,615",51%,2018
17,18,The Fate of the Furious,1236005118,"$226,008,385",18.3%,"$1,009,996,733",81.7%,2017
18,19,Iron Man Three,1214811252,"$409,013,994",33.7%,"$805,797,258",66.3%,2013
19,20,Minions,1159398397,"$336,045,770",29%,"$823,352,627",71%,2015
20,21,Captain America: Civil War,1153296293,"$408,084,349",35.4%,"$745,211,944",64.6%,2016
21,22,Aquaman,1148161807,"$335,061,807",29.2%,"$813,100,000",70.8%,2018
22,23,Spider-Man: Far from Home,1131845802,"$390,532,085",34.5%,"$741,313,717",65.5%,2019
23,24,Captain Marvel,1128274794,"$426,829,839",37.8%,"$701,444,955",62.2%,2019
24,25,Transformers: Dark of the Moon,1123794079,"$352,390,543",31.4%,"$771,403,536",68.6%,2011
25,26,The Lord of the Rings: The Return of the King,1120424614,"$377,845,905",33.7%,"$742,578,709",66.3%,2003
26,27,Skyfall,1108561013,"$304,360,277",27.5%,"$804,200,736",72.5%,2012
27,28,Transformers: Age of Extinction,1104054072,"$245,439,076",22.2%,"$858,614,996",77.8%,2014
28,29,The Dark Knight Rises,1081041287,"$448,139,099",41.4%,"$632,902,188",58.6%,2012
29,30,Toy Story 4,1073166397,"$433,954,795",40.4%,"$639,211,602",59.6%,2019
...,...,...,...,...,...,...,...,...
170,171,Fifty Shades of Grey,569651467,"$166,167,230",29.2%,"$403,484,237",70.8%,2015
171,172,Kong: Skull Island,566652812,"$168,052,812",29.7%,"$398,600,000",70.3%,2017
172,173,The Smurfs,563749323,"$142,614,158",25.3%,"$421,135,165",74.7%,2011
173,174,Cars 2,559852396,"$191,452,396",34.2%,"$368,400,000",65.8%,2011
174,175,Puss in Boots,554987477,"$149,260,504",26.9%,"$405,726,973",73.1%,2011
175,176,Mei ren yu,553810228,"$3,232,685",0.6%,"$550,577,543",99.4%,2016
176,177,Armageddon,553709788,"$201,578,182",36.4%,"$352,131,606",63.6%,1998
177,178,King Kong,550517357,"$218,080,025",39.6%,"$332,437,332",60.4%,2005
178,179,Ted,549368315,"$218,815,487",39.8%,"$330,552,828",60.2%,2012
179,180,Star Wars: Episode V - The Empire Strikes Back,547879454,"$290,271,960",53%,"$257,607,494",47%,1980
180,181,American Sniper,547426372,"$350,126,372",64%,"$197,300,000",36%,2014
181,182,Mission: Impossible II,546388105,"$215,409,889",39.4%,"$330,978,216",60.6%,2000
182,183,Tang ren jie tan an 2,544061916,"$1,983,984",0.4%,"$542,077,932",99.6%,2018
183,184,X-Men: Apocalypse,543934105,"$155,442,489",28.6%,"$388,491,616",71.4%,2016
184,185,Sherlock Holmes: A Game of Shadows,543848418,"$186,848,418",34.4%,"$357,000,000",65.6%,2011
185,186,Despicable Me,543113985,"$251,513,985",46.3%,"$291,600,000",53.7%,2010
186,187,The Day After Tomorrow,542771772,"$186,740,799",34.4%,"$356,030,973",65.6%,2004
187,188,Cinderella,542351353,"$201,151,353",37.1%,"$341,200,000",62.9%,2015
188,189,Madagascar,542063846,"$193,595,521",35.7%,"$348,468,325",64.3%,2005
189,190,World War Z,540007876,"$202,359,711",37.5%,"$337,648,165",62.5%,2013
190,191,Brave,538983207,"$237,283,207",44%,"$301,700,000",56%,2012
191,192,The Revenant,532950503,"$183,637,894",34.5%,"$349,312,609",65.5%,2015
192,193,The Meg,530243742,"$145,443,742",27.4%,"$384,800,000",72.6%,2018
193,194,Ralph Breaks the Internet,529323962,"$201,091,711",38%,"$328,232,251",62%,2018
194,195,Hotel Transylvania 3: Summer Vacation,528583774,"$167,510,016",31.7%,"$361,073,758",68.3%,2018
195,196,The Boss Baby,527965936,"$175,003,033",33.2%,"$352,962,903",66.8%,2017
196,197,The Simpsons Movie,527071022,"$183,135,014",34.8%,"$343,936,008",65.2%,2007
197,198,Dunkirk,526940665,"$189,740,665",36%,"$337,200,000",64%,2017
198,199,Godzilla,524976069,"$200,676,069",38.2%,"$324,300,000",61.8%,2014
199,200,Sherlock Holmes,524028679,"$209,028,679",39.9%,"$315,000,000",60.1%,2009

In [3]:
#We need to select data from 2008
def select_boxOfficemovieFrom(df,from_year):
    '''Require a value of year from which we select data'''
    data = df.copy().loc[(df['Year'] >= from_year)]
    return data

dt = select_boxOfficemovieFrom(dataDF,2008)
dt.shape

(150, 8)

In [9]:
import json
def pipe_flatten_names(keywords):
        return '|'.join([x['name'] for x in keywords])

In [ ]:
def safe_access(container, index_values):
    # return a missing value rather than an error upon indexing/key failure
    result = container
    try:
        for idx in index_values:
            result = result[idx]
        return result
    except IndexError or KeyError:
        return pd.np.nan

In [48]:
import json
import pandas as pd
def load_movies(path):
    df = pd.read_csv(path)
    #Show only year on date-release
    df['release_date'] = pd.to_datetime(df['release_date']).apply(lambda x: x.year)
    json_columns = ['genres', 'production_countries']
    for column in json_columns:
        df[column] = df[column].apply(json.loads)
    df['country'] = df['production_countries'].apply(lambda x: safe_access(x, [0, 'name']))
    df['genres'] = df['genres'].apply(pipe_flatten_names)

    return df
tmdb = load_movies(path +'/tmdb_5000_movies.csv')# Data from Kaggle, tmdb_movies
tmdb

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,country
0,237000000,Action|Adventure|Fantasy|Science Fiction,http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009.0,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,United States of America
1,300000000,Adventure|Fantasy|Action,http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007.0,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,United States of America
2,245000000,Action|Adventure|Crime,http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015.0,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,United Kingdom
3,250000000,Action|Crime|Drama|Thriller,http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012.0,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,United States of America
4,260000000,Action|Adventure|Science Fiction,http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012.0,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,United States of America
5,258000000,Fantasy|Action|Adventure,http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2007.0,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576,United States of America
6,260000000,Animation|Family,http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2010.0,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330,United States of America
7,280000000,Action|Adventure|Science Fiction,http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...",...,2015.0,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767,United States of America
8,250000000,Adventure|Fantasy|Family,http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...",...,2009.0,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293,United Kingdom
9,250000000,Action|Adventure|Fantasy,http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...",...,2016.0,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004,United States of America
10,270000000,Adventure|Fantasy|Action|Science Fiction,http://www.superman.com,1452,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Superman Returns,Superman returns to discover his 5-year absenc...,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...",...,2006.0,391081192,154.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Superman Returns,5.4,1400,United States of America
11,200000000,Adventure|Action|Thriller|Crime,http://www.mgm.com/view/movie/234/Quantum-of-S...,10764,"[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",en,Quantum of Solace,Quantum of Solace continues the adventures of ...,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]",...,2008.0,586090727,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965,United Kingdom
12,200000000,Adventure|Fantasy|Action,http://disney.go.com/disneypictures/pirates/,58,"[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",en,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,145.847379,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2006.0,1065659812,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246,Jamaica
13,255000000,Action|Adventure|Western,http://disney.go.com/the-lone-ranger/,57201,"[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2013.0,89289910,149.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never Take Off the Mask,The Lone Ranger,5.9,2311,United States of America
14,225000000,Action|Adventure|Fantasy|Science Fiction,http://www.manofsteel.com/,49521,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Man of Steel,A young boy learns that he has extraordinary p...,99.398009,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2013.0,662845518,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You will believe that a man can fly.,Man of Steel,6.5,6359,United Kingdom
15,225000000,Adventure|Family|Fantasy,NaN,2454,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...,53.978602,"[{""name"": ""Walt Disney"", ""id"": 5888}, {""name"":...",...,2008.0,419651413,150.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630,Czech Republic
16,220000000,Science Fiction|Action|Adventure,http://marvel.com/avengers_movie/,24428,"[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",en,The Avengers,When an unexpected enemy emerges and threatens...,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,2012.0,1519557910,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Some assembly required.,The Avengers,7.4,11776,United States of America
17,380000000,Adventure|Action|Fantasy,http://disney.go.com/pirates/index-on-stranger...,1865,"[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,135.413856,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2011.0,1045713802,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948,United States of America
18,225000000,Action|Comedy|Science Fiction,http://www.sonypictures.com/movies/meninblack3/,41154,"[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",en,Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,"[{""name"": ""Amblin Entertainment"", ""id"": 56}, {...",...,2012.0,624026776,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They are back... in time.,Men in Black 3,6.2,4160,United States of America
19,250000000,Action|Adventure|Fantasy,http://www.thehobbit.com/,122917,"[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",en,The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...,120.965743,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...",...,2014.0,956019788,144.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760,New Zealand
20,215000000,Action|Adventure|Fantasy,http://www.theamazingspiderman.com,1930,"[{""id"": 1872, ""name"": ""loss of father""}, {""id""...",en,The Amazing Spider-Man,Peter Parker is an outcast high schooler aband...,89.866276,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2012.0,752215857,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The untold story begins.,The Amazing Spider-Man,6.5,6586,United States of America
21,200000000,Action|Adventure,http://www.robinhoodthemovie.com/,20662,"[{""id"": 4147, ""name"": ""robin hood""}, {""id"": 43...",en,Robin Hood,When soldier Robin happens upon the dying Robe...,37.668301,"[{""name"": ""Imagine Entertainment"", ""id"": 23}, ...",...,2010.0,310669540,140.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"Rise and rise again, until lambs become lions.",Robin Hood,6.2,1398,United Kingdom
22,250000000,Adventure|Fantasy,http://www.thehobbit.com/,57158,"[{""id"": 603, ""name"": ""elves""}, {""id"": 604, ""na...",en,The Hobbit: The Desolation of Smaug,"The Dwarves, Bilbo and Gandalf have successful...",94.370564,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...",...,2013.0,958400000,161.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Beyond darkness... beyond desolation... lies t...,The Hobbit: The Desolation of Smaug,7.6,4524,New Zealand
23,180000000,Adventure|Fantasy,http://www.goldencompassmovie.com/index_german...,2268,"[{""id"": 392, ""name"": ""england""}, {""id"": 1461, ...",en,The Golden Compass,"After overhearing a shocking secret, precociou...",42.990906,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...",...,2007.0,372234864,113.0,"[{""iso_639_1"": ""is"", ""name"": ""\u00cdslenska""},...",Released,There are worlds beyond our own - the compass ...,The Golden Compass,5.8,1303,United Kingdom
24,207000000,Adventure|Drama|Action,NaN,254,"[{""id"": 774, ""name"": ""film business""}, {""id"": ...",en,King Kong,"In 1933 New York, an overly ambitious movie pr...",61.226010,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...",...,2005.0,550000000,187.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The eighth wonder of the world.,King Kong,6.6,2337,New Zealand
25,200000000,Drama|Romance|Thriller,http://www.titanicmovie.com,597,"[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",en,Titanic,"84 years later, a 101-year-old woman named Ros...",100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,1997.0,1845034188,194.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Nothing on Earth could come between them.,Titanic,7.5,7562,United States of America
26,250000000,Adventure|Action|Science Fiction,http://marvel.com/captainamericapremiere,271110,"[{""id"": 393, ""name"": ""civil war""}, {""id"": 6091...",en,Captain America: Civil War,"Following the events of Age of Ultron, the col...",198.372395,"[{""name"": ""Studio Babelsberg"", ""id"": 264}, {""n...",...,2016.0,1153304495,147.0,"[{""iso_639_1"": ""ro"", ""name"": ""Rom\u00e2n\u0103...",Released,Divided We Fall,Captain America: Civil War,7.1,7241,United States of America
27,209000000,Thriller|Action|Adventure|Science Fiction,NaN,44833,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 4410, ""...",en,Battleship,"When mankind beams a radio signal into space, ...",64.928382,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,2012.0,303025485,131.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The Battle for Earth Begins at Sea,Battleship,5.5,2114,United States of America
28,150000000,Action|Adventure|Science Fiction|Thriller,http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...",...,2015.0,1513528810,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The park is open.,Jurassic World,6.5,8662,United States of America
29,200000000,Action|Adventure|Thriller,http://www.skyfall-movie.com,37724,"[{""id"": 470, ""name"": ""spy""}, {""id"": 4289, ""nam...",en,Skyfall,When Bond's latest assignment goes gravely wro...,93.004993,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,2012.0,1108561013,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Think on your sins.,Skyfall,6.9,7604,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4773,27000,Comedy,http://www.miramax.com/movie/clerks/,2292,"[{""id"": 1361, ""name"": ""salesclerk""}, {""id"": 30...",en,Clerks,Convenience and video store clerks Dante and R...,19.748658,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",...,1994.0,3151130,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Just because they serve you doesn't mean they ...,Clerks,7.4,755,United States of America
4774,27000,Drama|Romance,NaN,42497,"[{""id"": 1566, ""name"": ""dream""}, {""id"": 13059, ...",en,Pink Narcissus,An erotic poem set in the fantasies of a young...,0.027811,"[{""name"": ""Strand Releasing"", ""id"": 3923}]",...,1971.0,0,64.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,A unique experience in visual fantasy!,Pink Narcissus,6.0,9,United States of America
4775,0,Drama|Comedy,NaN,33693,"[{""id"": 171993, ""name"": ""mumblecore""}]",en,Funny Ha Ha,"Unsure of what to do next, 23-year-old Marnie ...",0.362633,[],...,2002.0,76901,85.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Funny Ha Ha,6.3,8,United States of America
4776,0,Comedy|Drama,NaN,14585,"[{""id"": 1438, ""name"": ""office""}, {""id"": 9673, ...",en,In the Company of Men,Two business executives--one an avowed misogyn...,2.634007,"[{""name"": ""Alliance Atlantis Communications"", ...",...,1997.0,0,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Are all men bastards...or just misunderstood?,In the Company of Men,6.8,44,Canada
4777,0,Drama,NaN,185465,[],en,Manito,"Fifteen years ago, their Washington Heights ne...",0.039264,[],...,2002.0,0,78.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...",Released,NaN,Manito,5.5,2,United States of America
4778,0,Action|Drama|Crime|Thriller,NaN,38780,"[{""id"": 10022, ""name"": ""rampage""}, {""id"": 1454...",en,Rampage,The boredom of small town life is eating Bill ...,7.101197,"[{""name"": ""Boll Kino Beteiligungs GmbH & Co. K...",...,2009.0,0,85.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Vengeance is ruthless.,Rampage,6.0,131,Canada
4779,0,Comedy,NaN,14022,"[{""id"": 305, ""name"": ""moon""}, {""id"": 490, ""nam...",en,Slacker,"Presents a day in the life in Austin, Texas am...",3.320622,[],...,1990.0,0,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Slacker,6.4,77,United States of America
4780,0,Thriller|Crime|Drama,NaN,366967,[],en,Dutch Kills,A desperate ex-con is forced to gather his old...,0.038143,[],...,2015.0,0,90.0,[],Released,NaN,Dutch Kills,0.0,0,NaN
4781,22000,Comedy|Romance,https://www.facebook.com/DrySpellMovie,255266,"[{""id"": 13043, ""name"": ""dating""}, {""id"": 15160...",en,Dry Spell,Sasha tries to get her soon-to-be ex husband K...,0.048948,[],...,2013.0,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Getting divorced does funny things to a girl,Dry Spell,6.0,1,United States of America
4782,0,Drama|Family,NaN,17345,"[{""id"": 186, ""name"": ""christianity""}, {""id"": 4...",en,Flywheel,"Jay Austin wants to sell you a used car, but w...",1.048524,[],...,2003.0,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Flywheel,6.8,19,United States of America
4783,0,Thriller|Horror,NaN,226458,"[{""id"": 9712, ""name"": ""possession""}]",en,Backmask,"During an all-night, drug-fueled party at an a...",3.619167,"[{""name"": ""GO Productions"", ""id"": 2943}, {""nam...",...,2015.0,0,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,nederlands,Backmask,4.7,79,United States of America
4784,0,Drama|Comedy|Romance,http://www.thepuffychairmovie.com,24055,"[{""id"": 171993, ""name"": ""mumblecore""}]",en,The Puffy Chair,Josh's life is pretty much in the toilet. He's...,1.243955,[],...,2005.0,0,85.0,[],Released,NaN,The Puffy Chair,6.2,15,NaN
4785,0,Drama,NaN,287625,[],en,Stories of Our Lives,Created by the members of a Nairobi-based arts...,0.327794,[],...,2014.0,0,60.0,"[{""iso_639_1"": ""sw"", ""name"": ""Kiswahili""}, {""i...",Released,NaN,Stories of Our Lives,0.0,0,Kenya
4786,0,Comedy|Romance,NaN,44990,"[{""id"": 10183, ""name"": ""independent film""}]",en,Breaking Upwards,"'Breaking Upwards' explores a young, real-life...",0.674570,[],...,2009.0,0,88.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Breaking Upwards,5.6,12,United States of America
4787,0,Science Fiction|Thriller,NaN,86304,"[{""id"": 9715, ""name"": ""superhero""}]",en,All Superheroes Must Die,"Masked vigilantes Charge (Jason Trost), Cutthr...",3.545991,"[{""name"": ""Grindfest"", ""id"": 18818}]",...,2011.0,0,78.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,May The Best Man Win,All Superheroes Must Die,4.2,13,NaN
4788,12000,Horror|Comedy|Crime,NaN,692,"[{""id"": 237, ""name"": ""gay""}, {""id"": 900, ""name...",en,Pink Flamingos,Notorious Baltimore criminal and underground f...,4.553644,"[{""name"": ""Dreamland Productions"", ""id"": 407}]",...,1972.0,6000000,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,An exercise in poor taste.,Pink Flamingos,6.2,110,United States of America
4789,0,Drama,NaN,39851,"[{""id"": 6782, ""name"": ""addiction""}, {""id"": 155...",en,Clean,"After losing her husband to a heroin overdose,...",1.464566,[],...,2004.0,0,111.0,"[{""iso_639_1"": ""cn"", ""name"": ""\u5e7f\u5dde\u8b...",Released,"When you don't have a choice, you change.",Clean,6.7,17,United Kingdom
4790,0,Drama|Foreign,NaN,13898,[],fa,دایره,Various women struggle to function in the oppr...,1.193779,"[{""name"": ""Jafar Panahi Film Productions"", ""id...",...,2000.0,0,90.0,"[{""iso_639_1"": ""fa"", ""name"": ""\u0641\u0627\u06...",Released,NaN,The Circle,6.6,17,Iran

In [65]:
#retain only data from 2008
data = tmdbDF.copy().loc[(tmdbDF['release_date'] >= 2008)].sort_values(['revenue'],ascending=[False])
#data.head(4)
data.shape

(1920, 7)

cleaning data

In [53]:
data['title'].drop_duplicates()

0                                            Avatar
16                                     The Avengers
28                                   Jurassic World
44                                        Furious 7
7                           Avengers: Age of Ultron
124                                          Frozen
31                                       Iron Man 3
546                                         Minions
26                       Captain America: Civil War
52                   Transformers: Dark of the Moon
29                                          Skyfall
36                  Transformers: Age of Extinction
3                             The Dark Knight Rises
42                                      Toy Story 3
17      Pirates of the Caribbean: On Stranger Tides
32                              Alice in Wonderland
98                The Hobbit: An Unexpected Journey
65                                  The Dark Knight
506                                 Despicable Me 2
78                                  The Jungle Book
22              The Hobbit: The Desolation of Smaug
19        The Hobbit: The Battle of the Five Armies
8            Harry Potter and the Half-Blood Prince
348                  Ice Age: Dawn of the Dinosaurs
2                                           Spectre
325                      Ice Age: Continental Drift
504                         The Secret Life of Pets
9                Batman v Superman: Dawn of Justice
77                                       Inside Out
183                 The Hunger Games: Catching Fire
                           ...
3857                                   Wicked Blood
3859                                Lords of London
2273                                 Hands of Stone
2256    The Oogieloves in the Big Balloon Adventure
3863                                         August
2251                                My All American
2246                           Synecdoche, New York
3868                      To Write Love on Her Arms
2242                                Flash of Genius
2241                                  Passchendaele
3849                               The Masked Saint
2260                                All Good Things
3843                                      Sharknado
3840                                          Train
3788                               Guten Tag, Ramón
3797                                   Futuro Beach
2272                                        Dwegons
2271                                      Ramanujan
3803                                    Inescapable
3806                                       The Veil
3807                                 The Loved Ones
3808                                    The Helpers
3809                            How to Fall in Love
3810                               The Perfect Wave
3814                                  Desert Dancer
2270                                       Zambezia
3821                                 The Good Heart
3826                               Chain of Command
2268     Three Kingdoms: Resurrection of the Dragon
4801                               Shanghai Calling
Name: title, Length: 1920, dtype: object

In [54]:
data.isnull().sum()

id               0
title            0
genres           0
release_date     0
revenue          0
budget           0
country         87
dtype: int64

Rassembler les données

In [36]:
#load the boxoffice data made wit tmdb data
boxDF = load_data('boxoffice.csv')
boxDF.shape

(1920, 7)

In [25]:
df2 = budgetDF.rename({'Title': 'title', 'Worldwide Lifetime Gross': 'revenue'}, axis=1)  # rename column of data from Mojo
df2

,Rank,title,revenue,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,Year
0,1,Avengers: Endgame,2797800564,"$858,373,000",30.7%,"$1,939,427,564",69.3%,2019
1,2,Avatar,2789968301,"$760,507,625",27.3%,"$2,029,460,676",72.7%,2009
2,3,Titanic,2187463944,"$659,363,944",30.1%,"$1,528,100,000",69.9%,1997
3,4,Star Wars: Episode VII - The Force Awakens,2068223624,"$936,662,225",45.3%,"$1,131,561,399",54.7%,2015
4,5,Avengers: Infinity War,2048359754,"$678,815,482",33.1%,"$1,369,544,272",66.9%,2018
5,6,Jurassic World,1670400637,"$652,270,625",39%,"$1,018,130,012",61%,2015
6,7,The Lion King,1655151910,"$543,491,835",32.8%,"$1,111,660,075",67.2%,2019
7,8,The Avengers,1518812988,"$623,357,910",41%,"$895,455,078",59%,2012
8,9,Furious Seven,1515047671,"$353,007,020",23.3%,"$1,162,040,651",76.7%,2015
9,10,Avengers: Age of Ultron,1402805868,"$459,005,868",32.7%,"$943,800,000",67.3%,2015
10,11,Black Panther,1346913161,"$700,059,566",52%,"$646,853,595",48%,2018
11,12,Harry Potter and the Deathly Hallows: Part 2,1341932398,"$381,409,310",28.4%,"$960,523,088",71.6%,2011
12,13,Star Wars: Episode VIII - The Last Jedi,1332539889,"$620,181,382",46.5%,"$712,358,507",53.5%,2017
13,14,Jurassic World: Fallen Kingdom,1308467944,"$417,719,760",31.9%,"$890,748,184",68.1%,2018
14,15,Frozen,1274219009,"$400,738,009",31.4%,"$873,481,000",68.6%,2013
15,16,Beauty and the Beast,1263521126,"$504,014,165",39.9%,"$759,506,961",60.1%,2017
16,17,Incredibles 2,1242805359,"$608,581,744",49%,"$634,223,615",51%,2018
17,18,The Fate of the Furious,1236005118,"$226,008,385",18.3%,"$1,009,996,733",81.7%,2017
18,19,Iron Man Three,1214811252,"$409,013,994",33.7%,"$805,797,258",66.3%,2013
19,20,Minions,1159398397,"$336,045,770",29%,"$823,352,627",71%,2015
20,21,Captain America: Civil War,1153296293,"$408,084,349",35.4%,"$745,211,944",64.6%,2016
21,22,Aquaman,1148161807,"$335,061,807",29.2%,"$813,100,000",70.8%,2018
22,23,Spider-Man: Far from Home,1131845802,"$390,532,085",34.5%,"$741,313,717",65.5%,2019
23,24,Captain Marvel,1128274794,"$426,829,839",37.8%,"$701,444,955",62.2%,2019
24,25,Transformers: Dark of the Moon,1123794079,"$352,390,543",31.4%,"$771,403,536",68.6%,2011
25,26,The Lord of the Rings: The Return of the King,1120424614,"$377,845,905",33.7%,"$742,578,709",66.3%,2003
26,27,Skyfall,1108561013,"$304,360,277",27.5%,"$804,200,736",72.5%,2012
27,28,Transformers: Age of Extinction,1104054072,"$245,439,076",22.2%,"$858,614,996",77.8%,2014
28,29,The Dark Knight Rises,1081041287,"$448,139,099",41.4%,"$632,902,188",58.6%,2012
29,30,Toy Story 4,1073166397,"$433,954,795",40.4%,"$639,211,602",59.6%,2019
...,...,...,...,...,...,...,...,...
170,171,Fifty Shades of Grey,569651467,"$166,167,230",29.2%,"$403,484,237",70.8%,2015
171,172,Kong: Skull Island,566652812,"$168,052,812",29.7%,"$398,600,000",70.3%,2017
172,173,The Smurfs,563749323,"$142,614,158",25.3%,"$421,135,165",74.7%,2011
173,174,Cars 2,559852396,"$191,452,396",34.2%,"$368,400,000",65.8%,2011
174,175,Puss in Boots,554987477,"$149,260,504",26.9%,"$405,726,973",73.1%,2011
175,176,Mei ren yu,553810228,"$3,232,685",0.6%,"$550,577,543",99.4%,2016
176,177,Armageddon,553709788,"$201,578,182",36.4%,"$352,131,606",63.6%,1998
177,178,King Kong,550517357,"$218,080,025",39.6%,"$332,437,332",60.4%,2005
178,179,Ted,549368315,"$218,815,487",39.8%,"$330,552,828",60.2%,2012
179,180,Star Wars: Episode V - The Empire Strikes Back,547879454,"$290,271,960",53%,"$257,607,494",47%,1980
180,181,American Sniper,547426372,"$350,126,372",64%,"$197,300,000",36%,2014
181,182,Mission: Impossible II,546388105,"$215,409,889",39.4%,"$330,978,216",60.6%,2000
182,183,Tang ren jie tan an 2,544061916,"$1,983,984",0.4%,"$542,077,932",99.6%,2018
183,184,X-Men: Apocalypse,543934105,"$155,442,489",28.6%,"$388,491,616",71.4%,2016
184,185,Sherlock Holmes: A Game of Shadows,543848418,"$186,848,418",34.4%,"$357,000,000",65.6%,2011
185,186,Despicable Me,543113985,"$251,513,985",46.3%,"$291,600,000",53.7%,2010
186,187,The Day After Tomorrow,542771772,"$186,740,799",34.4%,"$356,030,973",65.6%,2004
187,188,Cinderella,542351353,"$201,151,353",37.1%,"$341,200,000",62.9%,2015
188,189,Madagascar,542063846,"$193,595,521",35.7%,"$348,468,325",64.3%,2005
189,190,World War Z,540007876,"$202,359,711",37.5%,"$337,648,165",62.5%,2013
190,191,Brave,538983207,"$237,283,207",44%,"$301,700,000",56%,2012
191,192,The Revenant,532950503,"$183,637,894",34.5%,"$349,312,609",65.5%,2015
192,193,The Meg,530243742,"$145,443,742",27.4%,"$384,800,000",72.6%,2018
193,194,Ralph Breaks the Internet,529323962,"$201,091,711",38%,"$328,232,251",62%,2018
194,195,Hotel Transylvania 3: Summer Vacation,528583774,"$167,510,016",31.7%,"$361,073,758",68.3%,2018
195,196,The Boss Baby,527965936,"$175,003,033",33.2%,"$352,962,903",66.8%,2017
196,197,The Simpsons Movie,527071022,"$183,135,014",34.8%,"$343,936,008",65.2%,2007
197,198,Dunkirk,526940665,"$189,740,665",36%,"$337,200,000",64%,2017
198,199,Godzilla,524976069,"$200,676,069",38.2%,"$324,300,000",61.8%,2014
199,200,Sherlock Holmes,524028679,"$209,028,679",39.9%,"$315,000,000",60.1%,2009

In [34]:
mergedStuff = pd.merge(boxDF, df2, on=['title'], how='left')# Merge data from Mojo and from TMDB
mergedStuff

,id,title,genres,release_date,revenue_x,budget,country,Rank,revenue_y,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,Year
0,19995,Avatar,Action|Adventure|Fantasy|Science Fiction,2009.0,2787965087,237000000,United States of America,2.0,2789968301,"$760,507,625",27.3%,"$2,029,460,676",72.7%,2009.0
1,24428,The Avengers,Science Fiction|Action|Adventure,2012.0,1519557910,220000000,United States of America,8.0,1518812988,"$623,357,910",41%,"$895,455,078",59%,2012.0
2,135397,Jurassic World,Action|Adventure|Science Fiction|Thriller,2015.0,1513528810,150000000,United States of America,6.0,1670400637,"$652,270,625",39%,"$1,018,130,012",61%,2015.0
3,168259,Furious 7,Action,2015.0,1506249360,190000000,Japan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,99861,Avengers: Age of Ultron,Action|Adventure|Science Fiction,2015.0,1405403694,280000000,United States of America,10.0,1402805868,"$459,005,868",32.7%,"$943,800,000",67.3%,2015.0
5,109445,Frozen,Animation|Adventure|Family,2013.0,1274219009,150000000,United States of America,15.0,1274219009,"$400,738,009",31.4%,"$873,481,000",68.6%,2013.0
6,68721,Iron Man 3,Action|Adventure|Science Fiction,2013.0,1215439994,200000000,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,211672,Minions,Family|Animation|Adventure|Comedy,2015.0,1156730962,74000000,United States of America,20.0,1159398397,"$336,045,770",29%,"$823,352,627",71%,2015.0
8,271110,Captain America: Civil War,Adventure|Action|Science Fiction,2016.0,1153304495,250000000,United States of America,21.0,1153296293,"$408,084,349",35.4%,"$745,211,944",64.6%,2016.0
9,38356,Transformers: Dark of the Moon,Action|Science Fiction|Adventure,2011.0,1123746996,195000000,United States of America,25.0,1123794079,"$352,390,543",31.4%,"$771,403,536",68.6%,2011.0
10,37724,Skyfall,Action|Adventure|Thriller,2012.0,1108561013,200000000,United Kingdom,27.0,1108561013,"$304,360,277",27.5%,"$804,200,736",72.5%,2012.0
11,91314,Transformers: Age of Extinction,Science Fiction|Action|Adventure,2014.0,1091405097,210000000,United States of America,28.0,1104054072,"$245,439,076",22.2%,"$858,614,996",77.8%,2014.0
12,49026,The Dark Knight Rises,Action|Crime|Drama|Thriller,2012.0,1084939099,250000000,United States of America,29.0,1081041287,"$448,139,099",41.4%,"$632,902,188",58.6%,2012.0
13,10193,Toy Story 3,Animation|Family|Comedy,2010.0,1066969703,200000000,United States of America,31.0,1066969703,"$415,004,880",38.9%,"$651,964,823",61.1%,2010.0
14,1865,Pirates of the Caribbean: On Stranger Tides,Adventure|Action|Fantasy,2011.0,1045713802,380000000,United States of America,35.0,1045713802,"$241,071,802",23%,"$804,642,000",77%,2011.0
15,12155,Alice in Wonderland,Family|Fantasy|Adventure,2010.0,1025491110,200000000,United States of America,40.0,1025467110,"$334,191,110",32.6%,"$691,276,000",67.4%,2010.0
16,49051,The Hobbit: An Unexpected Journey,Adventure|Fantasy|Action,2012.0,1021103568,250000000,New Zealand,42.0,1017003568,"$303,003,568",29.8%,"$714,000,000",70.2%,2012.0
17,155,The Dark Knight,Drama|Action|Crime|Thriller,2008.0,1004558444,185000000,United Kingdom,43.0,1004934033,"$535,234,033",53.3%,"$469,700,000",46.7%,2008.0
18,93456,Despicable Me 2,Animation|Comedy|Family,2013.0,970761885,76000000,United States of America,46.0,970766005,"$368,065,385",37.9%,"$602,700,620",62.1%,2013.0
19,278927,The Jungle Book,Family|Adventure|Drama|Fantasy,2016.0,966550600,175000000,United Kingdom,49.0,966550600,"$364,001,123",37.7%,"$602,549,477",62.3%,2016.0
20,57158,The Hobbit: The Desolation of Smaug,Adventure|Fantasy,2013.0,958400000,250000000,New Zealand,53.0,958366855,"$258,366,855",27%,"$700,000,000",73%,2013.0
21,122917,The Hobbit: The Battle of the Five Armies,Action|Adventure|Fantasy,2014.0,956019788,250000000,New Zealand,54.0,956019788,"$255,119,788",26.7%,"$700,900,000",73.3%,2014.0
22,767,Harry Potter and the Half-Blood Prince,Adventure|Fantasy|Family,2009.0,933959197,250000000,United Kingdom,56.0,934326396,"$302,305,431",32.4%,"$632,020,965",67.6%,2009.0
23,8355,Ice Age: Dawn of the Dinosaurs,Animation|Comedy|Family|Adventure,2009.0,886686817,90000000,United States of America,62.0,886686817,"$196,573,705",22.2%,"$690,113,112",77.8%,2009.0
24,206647,Spectre,Action|Adventure|Crime,2015.0,880674609,245000000,United Kingdom,63.0,880674609,"$200,074,609",22.7%,"$680,600,000",77.3%,2015.0
25,57800,Ice Age: Continental Drift,Animation|Comedy|Adventure|Family,2012.0,877244782,95000000,United States of America,66.0,877244782,"$161,321,843",18.4%,"$715,922,939",81.6%,2012.0
26,328111,The Secret Life of Pets,Animation|Family,2016.0,875958308,75000000,United States of America,67.0,875457937,"$368,384,330",42.1%,"$507,073,607",57.9%,2016.0
27,209112,Batman v Superman: Dawn of Justice,Action|Adventure|Fantasy,2016.0,873260194,250000000,United States of America,68.0,873634919,"$330,360,194",37.8%,"$543,274,725",62.2%,2015.0
28,150540,Inside Out,Drama|Comedy|Animation|Family,2015.0,857611174,175000000,United States of America,73.0,857611174,"$356,461,711",41.6%,"$501,149,463",58.4%,2015.0
29,101299,The Hunger Games: Catching Fire,Adventure|Action|Science Fiction,2013.0,847423452,130000000,United States of America,71.0,865011746,"$424,668,047",49.1%,"$440,343,699",50.9%,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,256740,Wicked Blood,Action|Drama|Thriller,2014.0,0,3500000,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1891,241766,Lords of London,Crime|Mystery|Thriller,2014.0,0,3440000,United Kingdom,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1892,184341,Hands of Stone,Drama,2016.0,0,20000000,Panama,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1893,112937,The Oogieloves in the Big Balloon Adventure,Family,2012.0,0,0,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1894,86549,August,Drama,2011.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1895,334531,My All American,Drama,2015.0,0,20000000,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1896,4960,"Synecdoche, New York",Drama,2008.0,0,21000000,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1897,75861,To Write Love on Her Arms,Drama|Music,2015.0,0,3400000,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1898,14914,Flash of Genius,Drama,2008.0,0,0,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1899,14582,Passchendaele,Drama|Romance|War|History,2008.0,0,0,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1900,370464,The Masked Saint,Crime|Action,2016.0,0,0,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1901,46503,All Good Things,Drama|Mystery|Thriller|Crime|Romance,2010.0,0,0,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1902,205321,Sharknado,TV Movie|Horror,2013.0,0,1000000,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1903,22007,Train,Horror|Thriller,2008.0,0,0,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1904,242575,"Guten Tag, Ramón",Drama,2013.0,0,4000000,Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1905,227975,Futuro Beach,Drama,2014.0,0,0,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1906,239897,Dwegons,Animation,2014.0,0,0,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1907,280871,Ramanujan,Drama|History,2014.0,0,0,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1908,121676,Inescapable,Thriller|Romance,2012.0,0,0,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1909,257087,The Veil,Horror,2016.0,0,4000000,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1910,46420,The Loved Ones,Horror,2009.0,0,0,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1911,114635,The Helpers,Horror,2012.0,0,4000000,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1912,158150,How to Fall in Love,Comedy|Romance|TV Movie,2012.0,0,4000000,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1913,251979,The Perfect Wave,Romance|Adventure|Drama,2014.0,0,0,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1914,266102,Desert Dancer,Drama,2014.0,0,0,Morocco,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1915,133931,Zambezia,Comedy|Animation|Adventure|Family,2012.0,0,20000000,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1916,5178,The Good Heart,Drama|Comedy|Romance,2009.0,0,3800000,Denmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1917,352978,Chain of Command,Thriller|Adventure|Action,2015.0,0,5000000,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1918,14538,Three Kingdoms: Resurrection of the Dragon,Action|History|Drama,2008.0,0,0,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919,126186,Shanghai Calling,NaN,2012.0,0,0,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
#replace na value revenue 
mergedStuff['revenue_y'].fillna(mergedStuff['revenue_x'], inplace=True)
mergedStuff

,id,title,genres,release_date,revenue_x,budget,country,Rank,revenue_y,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,Year
0,19995,Avatar,Action|Adventure|Fantasy|Science Fiction,2009.0,2787965087,237000000,United States of America,2.0,2789968301,"$760,507,625",27.3%,"$2,029,460,676",72.7%,2009.0
1,24428,The Avengers,Science Fiction|Action|Adventure,2012.0,1519557910,220000000,United States of America,8.0,1518812988,"$623,357,910",41%,"$895,455,078",59%,2012.0
2,135397,Jurassic World,Action|Adventure|Science Fiction|Thriller,2015.0,1513528810,150000000,United States of America,6.0,1670400637,"$652,270,625",39%,"$1,018,130,012",61%,2015.0
3,168259,Furious 7,Action,2015.0,1506249360,190000000,Japan,NaN,1506249360,NaN,NaN,NaN,NaN,NaN
4,99861,Avengers: Age of Ultron,Action|Adventure|Science Fiction,2015.0,1405403694,280000000,United States of America,10.0,1402805868,"$459,005,868",32.7%,"$943,800,000",67.3%,2015.0
5,109445,Frozen,Animation|Adventure|Family,2013.0,1274219009,150000000,United States of America,15.0,1274219009,"$400,738,009",31.4%,"$873,481,000",68.6%,2013.0
6,68721,Iron Man 3,Action|Adventure|Science Fiction,2013.0,1215439994,200000000,China,NaN,1215439994,NaN,NaN,NaN,NaN,NaN
7,211672,Minions,Family|Animation|Adventure|Comedy,2015.0,1156730962,74000000,United States of America,20.0,1159398397,"$336,045,770",29%,"$823,352,627",71%,2015.0
8,271110,Captain America: Civil War,Adventure|Action|Science Fiction,2016.0,1153304495,250000000,United States of America,21.0,1153296293,"$408,084,349",35.4%,"$745,211,944",64.6%,2016.0
9,38356,Transformers: Dark of the Moon,Action|Science Fiction|Adventure,2011.0,1123746996,195000000,United States of America,25.0,1123794079,"$352,390,543",31.4%,"$771,403,536",68.6%,2011.0
10,37724,Skyfall,Action|Adventure|Thriller,2012.0,1108561013,200000000,United Kingdom,27.0,1108561013,"$304,360,277",27.5%,"$804,200,736",72.5%,2012.0
11,91314,Transformers: Age of Extinction,Science Fiction|Action|Adventure,2014.0,1091405097,210000000,United States of America,28.0,1104054072,"$245,439,076",22.2%,"$858,614,996",77.8%,2014.0
12,49026,The Dark Knight Rises,Action|Crime|Drama|Thriller,2012.0,1084939099,250000000,United States of America,29.0,1081041287,"$448,139,099",41.4%,"$632,902,188",58.6%,2012.0
13,10193,Toy Story 3,Animation|Family|Comedy,2010.0,1066969703,200000000,United States of America,31.0,1066969703,"$415,004,880",38.9%,"$651,964,823",61.1%,2010.0
14,1865,Pirates of the Caribbean: On Stranger Tides,Adventure|Action|Fantasy,2011.0,1045713802,380000000,United States of America,35.0,1045713802,"$241,071,802",23%,"$804,642,000",77%,2011.0
15,12155,Alice in Wonderland,Family|Fantasy|Adventure,2010.0,1025491110,200000000,United States of America,40.0,1025467110,"$334,191,110",32.6%,"$691,276,000",67.4%,2010.0
16,49051,The Hobbit: An Unexpected Journey,Adventure|Fantasy|Action,2012.0,1021103568,250000000,New Zealand,42.0,1017003568,"$303,003,568",29.8%,"$714,000,000",70.2%,2012.0
17,155,The Dark Knight,Drama|Action|Crime|Thriller,2008.0,1004558444,185000000,United Kingdom,43.0,1004934033,"$535,234,033",53.3%,"$469,700,000",46.7%,2008.0
18,93456,Despicable Me 2,Animation|Comedy|Family,2013.0,970761885,76000000,United States of America,46.0,970766005,"$368,065,385",37.9%,"$602,700,620",62.1%,2013.0
19,278927,The Jungle Book,Family|Adventure|Drama|Fantasy,2016.0,966550600,175000000,United Kingdom,49.0,966550600,"$364,001,123",37.7%,"$602,549,477",62.3%,2016.0
20,57158,The Hobbit: The Desolation of Smaug,Adventure|Fantasy,2013.0,958400000,250000000,New Zealand,53.0,958366855,"$258,366,855",27%,"$700,000,000",73%,2013.0
21,122917,The Hobbit: The Battle of the Five Armies,Action|Adventure|Fantasy,2014.0,956019788,250000000,New Zealand,54.0,956019788,"$255,119,788",26.7%,"$700,900,000",73.3%,2014.0
22,767,Harry Potter and the Half-Blood Prince,Adventure|Fantasy|Family,2009.0,933959197,250000000,United Kingdom,56.0,934326396,"$302,305,431",32.4%,"$632,020,965",67.6%,2009.0
23,8355,Ice Age: Dawn of the Dinosaurs,Animation|Comedy|Family|Adventure,2009.0,886686817,90000000,United States of America,62.0,886686817,"$196,573,705",22.2%,"$690,113,112",77.8%,2009.0
24,206647,Spectre,Action|Adventure|Crime,2015.0,880674609,245000000,United Kingdom,63.0,880674609,"$200,074,609",22.7%,"$680,600,000",77.3%,2015.0
25,57800,Ice Age: Continental Drift,Animation|Comedy|Adventure|Family,2012.0,877244782,95000000,United States of America,66.0,877244782,"$161,321,843",18.4%,"$715,922,939",81.6%,2012.0
26,328111,The Secret Life of Pets,Animation|Family,2016.0,875958308,75000000,United States of America,67.0,875457937,"$368,384,330",42.1%,"$507,073,607",57.9%,2016.0
27,209112,Batman v Superman: Dawn of Justice,Action|Adventure|Fantasy,2016.0,873260194,250000000,United States of America,68.0,873634919,"$330,360,194",37.8%,"$543,274,725",62.2%,2015.0
28,150540,Inside Out,Drama|Comedy|Animation|Family,2015.0,857611174,175000000,United States of America,73.0,857611174,"$356,461,711",41.6%,"$501,149,463",58.4%,2015.0
29,101299,The Hunger Games: Catching Fire,Adventure|Action|Science Fiction,2013.0,847423452,130000000,United States of America,71.0,865011746,"$424,668,047",49.1%,"$440,343,699",50.9%,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,256740,Wicked Blood,Action|Drama|Thriller,2014.0,0,3500000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1891,241766,Lords of London,Crime|Mystery|Thriller,2014.0,0,3440000,United Kingdom,NaN,0,NaN,NaN,NaN,NaN,NaN
1892,184341,Hands of Stone,Drama,2016.0,0,20000000,Panama,NaN,0,NaN,NaN,NaN,NaN,NaN
1893,112937,The Oogieloves in the Big Balloon Adventure,Family,2012.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1894,86549,August,Drama,2011.0,0,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1895,334531,My All American,Drama,2015.0,0,20000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1896,4960,"Synecdoche, New York",Drama,2008.0,0,21000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1897,75861,To Write Love on Her Arms,Drama|Music,2015.0,0,3400000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1898,14914,Flash of Genius,Drama,2008.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1899,14582,Passchendaele,Drama|Romance|War|History,2008.0,0,0,Canada,NaN,0,NaN,NaN,NaN,NaN,NaN
1900,370464,The Masked Saint,Crime|Action,2016.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1901,46503,All Good Things,Drama|Mystery|Thriller|Crime|Romance,2010.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1902,205321,Sharknado,TV Movie|Horror,2013.0,0,1000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1903,22007,Train,Horror|Thriller,2008.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1904,242575,"Guten Tag, Ramón",Drama,2013.0,0,4000000,Mexico,NaN,0,NaN,NaN,NaN,NaN,NaN
1905,227975,Futuro Beach,Drama,2014.0,0,0,Brazil,NaN,0,NaN,NaN,NaN,NaN,NaN
1906,239897,Dwegons,Animation,2014.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1907,280871,Ramanujan,Drama|History,2014.0,0,0,India,NaN,0,NaN,NaN,NaN,NaN,NaN
1908,121676,Inescapable,Thriller|Romance,2012.0,0,0,Canada,NaN,0,NaN,NaN,NaN,NaN,NaN
1909,257087,The Veil,Horror,2016.0,0,4000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1910,46420,The Loved Ones,Horror,2009.0,0,0,Australia,NaN,0,NaN,NaN,NaN,NaN,NaN
1911,114635,The Helpers,Horror,2012.0,0,4000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1912,158150,How to Fall in Love,Comedy|Romance|TV Movie,2012.0,0,4000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1913,251979,The Perfect Wave,Romance|Adventure|Drama,2014.0,0,0,South Africa,NaN,0,NaN,NaN,NaN,NaN,NaN
1914,266102,Desert Dancer,Drama,2014.0,0,0,Morocco,NaN,0,NaN,NaN,NaN,NaN,NaN
1915,133931,Zambezia,Comedy|Animation|Adventure|Family,2012.0,0,20000000,South Africa,NaN,0,NaN,NaN,NaN,NaN,NaN
1916,5178,The Good Heart,Drama|Comedy|Romance,2009.0,0,3800000,Denmark,NaN,0,NaN,NaN,NaN,NaN,NaN
1917,352978,Chain of Command,Thriller|Adventure|Action,2015.0,0,5000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1918,14538,Three Kingdoms: Resurrection of the Dragon,Action|History|Drama,2008.0,0,0,China,NaN,0,NaN,NaN,NaN,NaN,NaN
1919,126186,Shanghai Calling,NaN,2012.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN

In [44]:
mergedStuff['title'].drop_duplicates()

(1920,)

In [43]:
#drop entries wit no genre , no title
new1 = mergedStuff.dropna(subset=['genres', 'title'])
new1

,id,title,genres,release_date,revenue_x,budget,country,Rank,revenue_y,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,Year
0,19995,Avatar,Action|Adventure|Fantasy|Science Fiction,2009.0,2787965087,237000000,United States of America,2.0,2789968301,"$760,507,625",27.3%,"$2,029,460,676",72.7%,2009.0
1,24428,The Avengers,Science Fiction|Action|Adventure,2012.0,1519557910,220000000,United States of America,8.0,1518812988,"$623,357,910",41%,"$895,455,078",59%,2012.0
2,135397,Jurassic World,Action|Adventure|Science Fiction|Thriller,2015.0,1513528810,150000000,United States of America,6.0,1670400637,"$652,270,625",39%,"$1,018,130,012",61%,2015.0
3,168259,Furious 7,Action,2015.0,1506249360,190000000,Japan,NaN,1506249360,NaN,NaN,NaN,NaN,NaN
4,99861,Avengers: Age of Ultron,Action|Adventure|Science Fiction,2015.0,1405403694,280000000,United States of America,10.0,1402805868,"$459,005,868",32.7%,"$943,800,000",67.3%,2015.0
5,109445,Frozen,Animation|Adventure|Family,2013.0,1274219009,150000000,United States of America,15.0,1274219009,"$400,738,009",31.4%,"$873,481,000",68.6%,2013.0
6,68721,Iron Man 3,Action|Adventure|Science Fiction,2013.0,1215439994,200000000,China,NaN,1215439994,NaN,NaN,NaN,NaN,NaN
7,211672,Minions,Family|Animation|Adventure|Comedy,2015.0,1156730962,74000000,United States of America,20.0,1159398397,"$336,045,770",29%,"$823,352,627",71%,2015.0
8,271110,Captain America: Civil War,Adventure|Action|Science Fiction,2016.0,1153304495,250000000,United States of America,21.0,1153296293,"$408,084,349",35.4%,"$745,211,944",64.6%,2016.0
9,38356,Transformers: Dark of the Moon,Action|Science Fiction|Adventure,2011.0,1123746996,195000000,United States of America,25.0,1123794079,"$352,390,543",31.4%,"$771,403,536",68.6%,2011.0
10,37724,Skyfall,Action|Adventure|Thriller,2012.0,1108561013,200000000,United Kingdom,27.0,1108561013,"$304,360,277",27.5%,"$804,200,736",72.5%,2012.0
11,91314,Transformers: Age of Extinction,Science Fiction|Action|Adventure,2014.0,1091405097,210000000,United States of America,28.0,1104054072,"$245,439,076",22.2%,"$858,614,996",77.8%,2014.0
12,49026,The Dark Knight Rises,Action|Crime|Drama|Thriller,2012.0,1084939099,250000000,United States of America,29.0,1081041287,"$448,139,099",41.4%,"$632,902,188",58.6%,2012.0
13,10193,Toy Story 3,Animation|Family|Comedy,2010.0,1066969703,200000000,United States of America,31.0,1066969703,"$415,004,880",38.9%,"$651,964,823",61.1%,2010.0
14,1865,Pirates of the Caribbean: On Stranger Tides,Adventure|Action|Fantasy,2011.0,1045713802,380000000,United States of America,35.0,1045713802,"$241,071,802",23%,"$804,642,000",77%,2011.0
15,12155,Alice in Wonderland,Family|Fantasy|Adventure,2010.0,1025491110,200000000,United States of America,40.0,1025467110,"$334,191,110",32.6%,"$691,276,000",67.4%,2010.0
16,49051,The Hobbit: An Unexpected Journey,Adventure|Fantasy|Action,2012.0,1021103568,250000000,New Zealand,42.0,1017003568,"$303,003,568",29.8%,"$714,000,000",70.2%,2012.0
17,155,The Dark Knight,Drama|Action|Crime|Thriller,2008.0,1004558444,185000000,United Kingdom,43.0,1004934033,"$535,234,033",53.3%,"$469,700,000",46.7%,2008.0
18,93456,Despicable Me 2,Animation|Comedy|Family,2013.0,970761885,76000000,United States of America,46.0,970766005,"$368,065,385",37.9%,"$602,700,620",62.1%,2013.0
19,278927,The Jungle Book,Family|Adventure|Drama|Fantasy,2016.0,966550600,175000000,United Kingdom,49.0,966550600,"$364,001,123",37.7%,"$602,549,477",62.3%,2016.0
20,57158,The Hobbit: The Desolation of Smaug,Adventure|Fantasy,2013.0,958400000,250000000,New Zealand,53.0,958366855,"$258,366,855",27%,"$700,000,000",73%,2013.0
21,122917,The Hobbit: The Battle of the Five Armies,Action|Adventure|Fantasy,2014.0,956019788,250000000,New Zealand,54.0,956019788,"$255,119,788",26.7%,"$700,900,000",73.3%,2014.0
22,767,Harry Potter and the Half-Blood Prince,Adventure|Fantasy|Family,2009.0,933959197,250000000,United Kingdom,56.0,934326396,"$302,305,431",32.4%,"$632,020,965",67.6%,2009.0
23,8355,Ice Age: Dawn of the Dinosaurs,Animation|Comedy|Family|Adventure,2009.0,886686817,90000000,United States of America,62.0,886686817,"$196,573,705",22.2%,"$690,113,112",77.8%,2009.0
24,206647,Spectre,Action|Adventure|Crime,2015.0,880674609,245000000,United Kingdom,63.0,880674609,"$200,074,609",22.7%,"$680,600,000",77.3%,2015.0
25,57800,Ice Age: Continental Drift,Animation|Comedy|Adventure|Family,2012.0,877244782,95000000,United States of America,66.0,877244782,"$161,321,843",18.4%,"$715,922,939",81.6%,2012.0
26,328111,The Secret Life of Pets,Animation|Family,2016.0,875958308,75000000,United States of America,67.0,875457937,"$368,384,330",42.1%,"$507,073,607",57.9%,2016.0
27,209112,Batman v Superman: Dawn of Justice,Action|Adventure|Fantasy,2016.0,873260194,250000000,United States of America,68.0,873634919,"$330,360,194",37.8%,"$543,274,725",62.2%,2015.0
28,150540,Inside Out,Drama|Comedy|Animation|Family,2015.0,857611174,175000000,United States of America,73.0,857611174,"$356,461,711",41.6%,"$501,149,463",58.4%,2015.0
29,101299,The Hunger Games: Catching Fire,Adventure|Action|Science Fiction,2013.0,847423452,130000000,United States of America,71.0,865011746,"$424,668,047",49.1%,"$440,343,699",50.9%,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1889,252360,In the Name of the King III,Action|Adventure|Drama|Fantasy,2013.0,0,3500000,Bulgaria,NaN,0,NaN,NaN,NaN,NaN,NaN
1890,256740,Wicked Blood,Action|Drama|Thriller,2014.0,0,3500000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1891,241766,Lords of London,Crime|Mystery|Thriller,2014.0,0,3440000,United Kingdom,NaN,0,NaN,NaN,NaN,NaN,NaN
1892,184341,Hands of Stone,Drama,2016.0,0,20000000,Panama,NaN,0,NaN,NaN,NaN,NaN,NaN
1893,112937,The Oogieloves in the Big Balloon Adventure,Family,2012.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1894,86549,August,Drama,2011.0,0,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1895,334531,My All American,Drama,2015.0,0,20000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1896,4960,"Synecdoche, New York",Drama,2008.0,0,21000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1897,75861,To Write Love on Her Arms,Drama|Music,2015.0,0,3400000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1898,14914,Flash of Genius,Drama,2008.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1899,14582,Passchendaele,Drama|Romance|War|History,2008.0,0,0,Canada,NaN,0,NaN,NaN,NaN,NaN,NaN
1900,370464,The Masked Saint,Crime|Action,2016.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1901,46503,All Good Things,Drama|Mystery|Thriller|Crime|Romance,2010.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1902,205321,Sharknado,TV Movie|Horror,2013.0,0,1000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1903,22007,Train,Horror|Thriller,2008.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1904,242575,"Guten Tag, Ramón",Drama,2013.0,0,4000000,Mexico,NaN,0,NaN,NaN,NaN,NaN,NaN
1905,227975,Futuro Beach,Drama,2014.0,0,0,Brazil,NaN,0,NaN,NaN,NaN,NaN,NaN
1906,239897,Dwegons,Animation,2014.0,0,0,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1907,280871,Ramanujan,Drama|History,2014.0,0,0,India,NaN,0,NaN,NaN,NaN,NaN,NaN
1908,121676,Inescapable,Thriller|Romance,2012.0,0,0,Canada,NaN,0,NaN,NaN,NaN,NaN,NaN
1909,257087,The Veil,Horror,2016.0,0,4000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1910,46420,The Loved Ones,Horror,2009.0,0,0,Australia,NaN,0,NaN,NaN,NaN,NaN,NaN
1911,114635,The Helpers,Horror,2012.0,0,4000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1912,158150,How to Fall in Love,Comedy|Romance|TV Movie,2012.0,0,4000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1913,251979,The Perfect Wave,Romance|Adventure|Drama,2014.0,0,0,South Africa,NaN,0,NaN,NaN,NaN,NaN,NaN
1914,266102,Desert Dancer,Drama,2014.0,0,0,Morocco,NaN,0,NaN,NaN,NaN,NaN,NaN
1915,133931,Zambezia,Comedy|Animation|Adventure|Family,2012.0,0,20000000,South Africa,NaN,0,NaN,NaN,NaN,NaN,NaN
1916,5178,The Good Heart,Drama|Comedy|Romance,2009.0,0,3800000,Denmark,NaN,0,NaN,NaN,NaN,NaN,NaN
1917,352978,Chain of Command,Thriller|Adventure|Action,2015.0,0,5000000,United States of America,NaN,0,NaN,NaN,NaN,NaN,NaN
1918,14538,Three Kingdoms: Resurrection of the Dragon,Action|History|Drama,2008.0,0,0,China,NaN,0,NaN,NaN,NaN,NaN,NaN

In [56]:
dataDF1= new1[new1['budget'] != 0]
dataCleaned = dataDF1[dataDF1['revenue_y'] != 0]
dataCleaned.shape
dataCleaned

,id,title,genres,release_date,revenue_x,budget,country,Rank,revenue_y,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,Year
0,19995,Avatar,Action|Adventure|Fantasy|Science Fiction,2009.0,2787965087,237000000,United States of America,2.0,2789968301,"$760,507,625",27.3%,"$2,029,460,676",72.7%,2009.0
1,24428,The Avengers,Science Fiction|Action|Adventure,2012.0,1519557910,220000000,United States of America,8.0,1518812988,"$623,357,910",41%,"$895,455,078",59%,2012.0
2,135397,Jurassic World,Action|Adventure|Science Fiction|Thriller,2015.0,1513528810,150000000,United States of America,6.0,1670400637,"$652,270,625",39%,"$1,018,130,012",61%,2015.0
3,168259,Furious 7,Action,2015.0,1506249360,190000000,Japan,NaN,1506249360,NaN,NaN,NaN,NaN,NaN
4,99861,Avengers: Age of Ultron,Action|Adventure|Science Fiction,2015.0,1405403694,280000000,United States of America,10.0,1402805868,"$459,005,868",32.7%,"$943,800,000",67.3%,2015.0
5,109445,Frozen,Animation|Adventure|Family,2013.0,1274219009,150000000,United States of America,15.0,1274219009,"$400,738,009",31.4%,"$873,481,000",68.6%,2013.0
6,68721,Iron Man 3,Action|Adventure|Science Fiction,2013.0,1215439994,200000000,China,NaN,1215439994,NaN,NaN,NaN,NaN,NaN
7,211672,Minions,Family|Animation|Adventure|Comedy,2015.0,1156730962,74000000,United States of America,20.0,1159398397,"$336,045,770",29%,"$823,352,627",71%,2015.0
8,271110,Captain America: Civil War,Adventure|Action|Science Fiction,2016.0,1153304495,250000000,United States of America,21.0,1153296293,"$408,084,349",35.4%,"$745,211,944",64.6%,2016.0
9,38356,Transformers: Dark of the Moon,Action|Science Fiction|Adventure,2011.0,1123746996,195000000,United States of America,25.0,1123794079,"$352,390,543",31.4%,"$771,403,536",68.6%,2011.0
10,37724,Skyfall,Action|Adventure|Thriller,2012.0,1108561013,200000000,United Kingdom,27.0,1108561013,"$304,360,277",27.5%,"$804,200,736",72.5%,2012.0
11,91314,Transformers: Age of Extinction,Science Fiction|Action|Adventure,2014.0,1091405097,210000000,United States of America,28.0,1104054072,"$245,439,076",22.2%,"$858,614,996",77.8%,2014.0
12,49026,The Dark Knight Rises,Action|Crime|Drama|Thriller,2012.0,1084939099,250000000,United States of America,29.0,1081041287,"$448,139,099",41.4%,"$632,902,188",58.6%,2012.0
13,10193,Toy Story 3,Animation|Family|Comedy,2010.0,1066969703,200000000,United States of America,31.0,1066969703,"$415,004,880",38.9%,"$651,964,823",61.1%,2010.0
14,1865,Pirates of the Caribbean: On Stranger Tides,Adventure|Action|Fantasy,2011.0,1045713802,380000000,United States of America,35.0,1045713802,"$241,071,802",23%,"$804,642,000",77%,2011.0
15,12155,Alice in Wonderland,Family|Fantasy|Adventure,2010.0,1025491110,200000000,United States of America,40.0,1025467110,"$334,191,110",32.6%,"$691,276,000",67.4%,2010.0
16,49051,The Hobbit: An Unexpected Journey,Adventure|Fantasy|Action,2012.0,1021103568,250000000,New Zealand,42.0,1017003568,"$303,003,568",29.8%,"$714,000,000",70.2%,2012.0
17,155,The Dark Knight,Drama|Action|Crime|Thriller,2008.0,1004558444,185000000,United Kingdom,43.0,1004934033,"$535,234,033",53.3%,"$469,700,000",46.7%,2008.0
18,93456,Despicable Me 2,Animation|Comedy|Family,2013.0,970761885,76000000,United States of America,46.0,970766005,"$368,065,385",37.9%,"$602,700,620",62.1%,2013.0
19,278927,The Jungle Book,Family|Adventure|Drama|Fantasy,2016.0,966550600,175000000,United Kingdom,49.0,966550600,"$364,001,123",37.7%,"$602,549,477",62.3%,2016.0
20,57158,The Hobbit: The Desolation of Smaug,Adventure|Fantasy,2013.0,958400000,250000000,New Zealand,53.0,958366855,"$258,366,855",27%,"$700,000,000",73%,2013.0
21,122917,The Hobbit: The Battle of the Five Armies,Action|Adventure|Fantasy,2014.0,956019788,250000000,New Zealand,54.0,956019788,"$255,119,788",26.7%,"$700,900,000",73.3%,2014.0
22,767,Harry Potter and the Half-Blood Prince,Adventure|Fantasy|Family,2009.0,933959197,250000000,United Kingdom,56.0,934326396,"$302,305,431",32.4%,"$632,020,965",67.6%,2009.0
23,8355,Ice Age: Dawn of the Dinosaurs,Animation|Comedy|Family|Adventure,2009.0,886686817,90000000,United States of America,62.0,886686817,"$196,573,705",22.2%,"$690,113,112",77.8%,2009.0
24,206647,Spectre,Action|Adventure|Crime,2015.0,880674609,245000000,United Kingdom,63.0,880674609,"$200,074,609",22.7%,"$680,600,000",77.3%,2015.0
25,57800,Ice Age: Continental Drift,Animation|Comedy|Adventure|Family,2012.0,877244782,95000000,United States of America,66.0,877244782,"$161,321,843",18.4%,"$715,922,939",81.6%,2012.0
26,328111,The Secret Life of Pets,Animation|Family,2016.0,875958308,75000000,United States of America,67.0,875457937,"$368,384,330",42.1%,"$507,073,607",57.9%,2016.0
27,209112,Batman v Superman: Dawn of Justice,Action|Adventure|Fantasy,2016.0,873260194,250000000,United States of America,68.0,873634919,"$330,360,194",37.8%,"$543,274,725",62.2%,2015.0
28,150540,Inside Out,Drama|Comedy|Animation|Family,2015.0,857611174,175000000,United States of America,73.0,857611174,"$356,461,711",41.6%,"$501,149,463",58.4%,2015.0
29,101299,The Hunger Games: Catching Fire,Adventure|Action|Science Fiction,2013.0,847423452,130000000,United States of America,71.0,865011746,"$424,668,047",49.1%,"$440,343,699",50.9%,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288,76349,1911,Adventure|Drama|Action|History|War,2011.0,108348,30000000,China,NaN,108348,NaN,NaN,NaN,NaN,NaN
1289,20764,Sleep Dealer,Drama|Science Fiction|Thriller,2008.0,107559,2500000,Mexico,NaN,107559,NaN,NaN,NaN,NaN,NaN
1290,43942,Freakonomics,Documentary,2010.0,103735,3000000,United States of America,NaN,103735,NaN,NaN,NaN,NaN,NaN
1291,45649,Rubber,Comedy|Drama|Fantasy|Horror|Mystery,2010.0,98017,500000,France,NaN,98017,NaN,NaN,NaN,NaN,NaN
1292,115210,Stitches,Horror,2012.0,95000,100000,Ireland,NaN,95000,NaN,NaN,NaN,NaN,NaN
1293,58428,The Innkeepers,Horror|Thriller,2011.0,78396,750000,United States of America,NaN,78396,NaN,NaN,NaN,NaN,NaN
1294,116977,Foodfight!,Animation|Action|Comedy|Family,2012.0,73706,65000000,United States of America,NaN,73706,NaN,NaN,NaN,NaN,NaN
1295,13827,"Surfer, Dude",Comedy,2008.0,69497,6000000,United States of America,NaN,69497,NaN,NaN,NaN,NaN,NaN
1296,97614,Deadfall,Crime|Drama|Thriller,2012.0,66351,12000000,France,NaN,66351,NaN,NaN,NaN,NaN,NaN
1297,109729,The Canyons,Thriller|Drama,2013.0,56825,250000,United States of America,NaN,56825,NaN,NaN,NaN,NaN,NaN
1298,251321,Aloft,Drama,2014.0,53086,8000000,France,NaN,53086,NaN,NaN,NaN,NaN,NaN
1299,44754,Margaret,Drama,2011.0,46495,14000000,United States of America,NaN,46495,NaN,NaN,NaN,NaN,NaN
1300,27004,Ca$h,Crime|Thriller|Comedy,2010.0,46488,7000000,United States of America,NaN,46488,NaN,NaN,NaN,NaN,NaN
1301,301748,The Opposite Sex,Comedy,2014.0,45000,3300000,United States of America,NaN,45000,NaN,NaN,NaN,NaN,NaN
1302,34769,Defendor,Drama|Action|Comedy|Crime,2009.0,44462,3500000,Canada,NaN,44462,NaN,NaN,NaN,NaN,NaN
1304,52015,Stake Land,Drama|Horror|Action|Thriller|Science Fiction,2010.0,33245,650000,United States of America,NaN,33245,NaN,NaN,NaN,NaN,NaN
1305,244783,Song One,Drama,2014.0,32251,6000000,United States of America,NaN,32251,NaN,NaN,NaN,NaN,NaN
1306,23963,Pontypool,Horror|Mystery|Science Fiction,2009.0,32000,1500000,Canada,NaN,32000,NaN,NaN,NaN,NaN,NaN
1307,103620,Maniac,Horror,2012.0,31081,6000000,France,NaN,31081,NaN,NaN,NaN,NaN,NaN
1308,91070,L!fe Happens,Comedy,2011.0,30905,930000,Canada,NaN,30905,NaN,NaN,NaN,NaN,NaN
1309,89750,"Pink Ribbons, Inc.",Documentary,2011.0,25000,900000,United States of America,NaN,25000,NaN,NaN,NaN,NaN,NaN
1310,38541,The Divide,Science Fiction,2011.0,22000,3000000,Canada,NaN,22000,NaN,NaN,NaN,NaN,NaN
1311,50601,5 Days of War,War|Drama,2011.0,17479,20000000,United States of America,NaN,17479,NaN,NaN,NaN,NaN,NaN
1312,245846,Strangerland,Drama|Thriller,2015.0,17472,10000000,Australia,NaN,17472,NaN,NaN,NaN,NaN,NaN
1314,42151,Down Terrace,Drama|Action|Comedy,2009.0,10000,31192,United Kingdom,NaN,10000,NaN,NaN,NaN,NaN,NaN
1315,25186,Janky Promoters,Comedy,2009.0,9069,10000000,United States of America,NaN,9069,NaN,NaN,NaN,NaN,NaN
1316,227707,The Adventurer: The Curse of the Midas Box,Fantasy|Adventure|Family,2013.0,6399,25000000,Belgium,NaN,6399,NaN,NaN,NaN,NaN,NaN
1317,364083,Mi America,Drama|Crime,2015.0,3330,2100000,United States of America,NaN,3330,NaN,NaN,NaN,NaN,NaN
1320,217708,Of Horses and Men,Drama|Romance|Comedy,2013.0,11,10,Norway,NaN,11,NaN,NaN,NaN,NaN,NaN
1321,38415,Bran Nue Dae,Comedy|Drama|Foreign|Romance,2009.0,7,7,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN

In [48]:
DataBox = dataCleaned.rename({'revenue_y': 'revenue'}, axis=1)  # 
DataBox

,id,title,genres,release_date,revenue_x,budget,country,Rank,revenue,Domestic Lifetime Gross,Domestic %,Foreign Lifetime Gross,Foreign %,Year
0,19995,Avatar,Action|Adventure|Fantasy|Science Fiction,2009.0,2787965087,237000000,United States of America,2.0,2789968301,"$760,507,625",27.3%,"$2,029,460,676",72.7%,2009.0
1,24428,The Avengers,Science Fiction|Action|Adventure,2012.0,1519557910,220000000,United States of America,8.0,1518812988,"$623,357,910",41%,"$895,455,078",59%,2012.0
2,135397,Jurassic World,Action|Adventure|Science Fiction|Thriller,2015.0,1513528810,150000000,United States of America,6.0,1670400637,"$652,270,625",39%,"$1,018,130,012",61%,2015.0
3,168259,Furious 7,Action,2015.0,1506249360,190000000,Japan,NaN,1506249360,NaN,NaN,NaN,NaN,NaN
4,99861,Avengers: Age of Ultron,Action|Adventure|Science Fiction,2015.0,1405403694,280000000,United States of America,10.0,1402805868,"$459,005,868",32.7%,"$943,800,000",67.3%,2015.0
5,109445,Frozen,Animation|Adventure|Family,2013.0,1274219009,150000000,United States of America,15.0,1274219009,"$400,738,009",31.4%,"$873,481,000",68.6%,2013.0
6,68721,Iron Man 3,Action|Adventure|Science Fiction,2013.0,1215439994,200000000,China,NaN,1215439994,NaN,NaN,NaN,NaN,NaN
7,211672,Minions,Family|Animation|Adventure|Comedy,2015.0,1156730962,74000000,United States of America,20.0,1159398397,"$336,045,770",29%,"$823,352,627",71%,2015.0
8,271110,Captain America: Civil War,Adventure|Action|Science Fiction,2016.0,1153304495,250000000,United States of America,21.0,1153296293,"$408,084,349",35.4%,"$745,211,944",64.6%,2016.0
9,38356,Transformers: Dark of the Moon,Action|Science Fiction|Adventure,2011.0,1123746996,195000000,United States of America,25.0,1123794079,"$352,390,543",31.4%,"$771,403,536",68.6%,2011.0
10,37724,Skyfall,Action|Adventure|Thriller,2012.0,1108561013,200000000,United Kingdom,27.0,1108561013,"$304,360,277",27.5%,"$804,200,736",72.5%,2012.0
11,91314,Transformers: Age of Extinction,Science Fiction|Action|Adventure,2014.0,1091405097,210000000,United States of America,28.0,1104054072,"$245,439,076",22.2%,"$858,614,996",77.8%,2014.0
12,49026,The Dark Knight Rises,Action|Crime|Drama|Thriller,2012.0,1084939099,250000000,United States of America,29.0,1081041287,"$448,139,099",41.4%,"$632,902,188",58.6%,2012.0
13,10193,Toy Story 3,Animation|Family|Comedy,2010.0,1066969703,200000000,United States of America,31.0,1066969703,"$415,004,880",38.9%,"$651,964,823",61.1%,2010.0
14,1865,Pirates of the Caribbean: On Stranger Tides,Adventure|Action|Fantasy,2011.0,1045713802,380000000,United States of America,35.0,1045713802,"$241,071,802",23%,"$804,642,000",77%,2011.0
15,12155,Alice in Wonderland,Family|Fantasy|Adventure,2010.0,1025491110,200000000,United States of America,40.0,1025467110,"$334,191,110",32.6%,"$691,276,000",67.4%,2010.0
16,49051,The Hobbit: An Unexpected Journey,Adventure|Fantasy|Action,2012.0,1021103568,250000000,New Zealand,42.0,1017003568,"$303,003,568",29.8%,"$714,000,000",70.2%,2012.0
17,155,The Dark Knight,Drama|Action|Crime|Thriller,2008.0,1004558444,185000000,United Kingdom,43.0,1004934033,"$535,234,033",53.3%,"$469,700,000",46.7%,2008.0
18,93456,Despicable Me 2,Animation|Comedy|Family,2013.0,970761885,76000000,United States of America,46.0,970766005,"$368,065,385",37.9%,"$602,700,620",62.1%,2013.0
19,278927,The Jungle Book,Family|Adventure|Drama|Fantasy,2016.0,966550600,175000000,United Kingdom,49.0,966550600,"$364,001,123",37.7%,"$602,549,477",62.3%,2016.0
20,57158,The Hobbit: The Desolation of Smaug,Adventure|Fantasy,2013.0,958400000,250000000,New Zealand,53.0,958366855,"$258,366,855",27%,"$700,000,000",73%,2013.0
21,122917,The Hobbit: The Battle of the Five Armies,Action|Adventure|Fantasy,2014.0,956019788,250000000,New Zealand,54.0,956019788,"$255,119,788",26.7%,"$700,900,000",73.3%,2014.0
22,767,Harry Potter and the Half-Blood Prince,Adventure|Fantasy|Family,2009.0,933959197,250000000,United Kingdom,56.0,934326396,"$302,305,431",32.4%,"$632,020,965",67.6%,2009.0
23,8355,Ice Age: Dawn of the Dinosaurs,Animation|Comedy|Family|Adventure,2009.0,886686817,90000000,United States of America,62.0,886686817,"$196,573,705",22.2%,"$690,113,112",77.8%,2009.0
24,206647,Spectre,Action|Adventure|Crime,2015.0,880674609,245000000,United Kingdom,63.0,880674609,"$200,074,609",22.7%,"$680,600,000",77.3%,2015.0
25,57800,Ice Age: Continental Drift,Animation|Comedy|Adventure|Family,2012.0,877244782,95000000,United States of America,66.0,877244782,"$161,321,843",18.4%,"$715,922,939",81.6%,2012.0
26,328111,The Secret Life of Pets,Animation|Family,2016.0,875958308,75000000,United States of America,67.0,875457937,"$368,384,330",42.1%,"$507,073,607",57.9%,2016.0
27,209112,Batman v Superman: Dawn of Justice,Action|Adventure|Fantasy,2016.0,873260194,250000000,United States of America,68.0,873634919,"$330,360,194",37.8%,"$543,274,725",62.2%,2015.0
28,150540,Inside Out,Drama|Comedy|Animation|Family,2015.0,857611174,175000000,United States of America,73.0,857611174,"$356,461,711",41.6%,"$501,149,463",58.4%,2015.0
29,101299,The Hunger Games: Catching Fire,Adventure|Action|Science Fiction,2013.0,847423452,130000000,United States of America,71.0,865011746,"$424,668,047",49.1%,"$440,343,699",50.9%,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288,76349,1911,Adventure|Drama|Action|History|War,2011.0,108348,30000000,China,NaN,108348,NaN,NaN,NaN,NaN,NaN
1289,20764,Sleep Dealer,Drama|Science Fiction|Thriller,2008.0,107559,2500000,Mexico,NaN,107559,NaN,NaN,NaN,NaN,NaN
1290,43942,Freakonomics,Documentary,2010.0,103735,3000000,United States of America,NaN,103735,NaN,NaN,NaN,NaN,NaN
1291,45649,Rubber,Comedy|Drama|Fantasy|Horror|Mystery,2010.0,98017,500000,France,NaN,98017,NaN,NaN,NaN,NaN,NaN
1292,115210,Stitches,Horror,2012.0,95000,100000,Ireland,NaN,95000,NaN,NaN,NaN,NaN,NaN
1293,58428,The Innkeepers,Horror|Thriller,2011.0,78396,750000,United States of America,NaN,78396,NaN,NaN,NaN,NaN,NaN
1294,116977,Foodfight!,Animation|Action|Comedy|Family,2012.0,73706,65000000,United States of America,NaN,73706,NaN,NaN,NaN,NaN,NaN
1295,13827,"Surfer, Dude",Comedy,2008.0,69497,6000000,United States of America,NaN,69497,NaN,NaN,NaN,NaN,NaN
1296,97614,Deadfall,Crime|Drama|Thriller,2012.0,66351,12000000,France,NaN,66351,NaN,NaN,NaN,NaN,NaN
1297,109729,The Canyons,Thriller|Drama,2013.0,56825,250000,United States of America,NaN,56825,NaN,NaN,NaN,NaN,NaN
1298,251321,Aloft,Drama,2014.0,53086,8000000,France,NaN,53086,NaN,NaN,NaN,NaN,NaN
1299,44754,Margaret,Drama,2011.0,46495,14000000,United States of America,NaN,46495,NaN,NaN,NaN,NaN,NaN
1300,27004,Ca$h,Crime|Thriller|Comedy,2010.0,46488,7000000,United States of America,NaN,46488,NaN,NaN,NaN,NaN,NaN
1301,301748,The Opposite Sex,Comedy,2014.0,45000,3300000,United States of America,NaN,45000,NaN,NaN,NaN,NaN,NaN
1302,34769,Defendor,Drama|Action|Comedy|Crime,2009.0,44462,3500000,Canada,NaN,44462,NaN,NaN,NaN,NaN,NaN
1304,52015,Stake Land,Drama|Horror|Action|Thriller|Science Fiction,2010.0,33245,650000,United States of America,NaN,33245,NaN,NaN,NaN,NaN,NaN
1305,244783,Song One,Drama,2014.0,32251,6000000,United States of America,NaN,32251,NaN,NaN,NaN,NaN,NaN
1306,23963,Pontypool,Horror|Mystery|Science Fiction,2009.0,32000,1500000,Canada,NaN,32000,NaN,NaN,NaN,NaN,NaN
1307,103620,Maniac,Horror,2012.0,31081,6000000,France,NaN,31081,NaN,NaN,NaN,NaN,NaN
1308,91070,L!fe Happens,Comedy,2011.0,30905,930000,Canada,NaN,30905,NaN,NaN,NaN,NaN,NaN
1309,89750,"Pink Ribbons, Inc.",Documentary,2011.0,25000,900000,United States of America,NaN,25000,NaN,NaN,NaN,NaN,NaN
1310,38541,The Divide,Science Fiction,2011.0,22000,3000000,Canada,NaN,22000,NaN,NaN,NaN,NaN,NaN
1311,50601,5 Days of War,War|Drama,2011.0,17479,20000000,United States of America,NaN,17479,NaN,NaN,NaN,NaN,NaN
1312,245846,Strangerland,Drama|Thriller,2015.0,17472,10000000,Australia,NaN,17472,NaN,NaN,NaN,NaN,NaN
1314,42151,Down Terrace,Drama|Action|Comedy,2009.0,10000,31192,United Kingdom,NaN,10000,NaN,NaN,NaN,NaN,NaN
1315,25186,Janky Promoters,Comedy,2009.0,9069,10000000,United States of America,NaN,9069,NaN,NaN,NaN,NaN,NaN
1316,227707,The Adventurer: The Curse of the Midas Box,Fantasy|Adventure|Family,2013.0,6399,25000000,Belgium,NaN,6399,NaN,NaN,NaN,NaN,NaN
1317,364083,Mi America,Drama|Crime,2015.0,3330,2100000,United States of America,NaN,3330,NaN,NaN,NaN,NaN,NaN
1320,217708,Of Horses and Men,Drama|Romance|Comedy,2013.0,11,10,Norway,NaN,11,NaN,NaN,NaN,NaN,NaN
1321,38415,Bran Nue Dae,Comedy|Drama|Foreign|Romance,2009.0,7,7,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN

In [53]:
movieDF  = select_only_interest(DataBox)
movieDF.head(10)

,id,title,genres,release_date,revenue,budget,country
0,19995,Avatar,Action|Adventure|Fantasy|Science Fiction,2009.0,2789968301,237000000,United States of America
1,24428,The Avengers,Science Fiction|Action|Adventure,2012.0,1518812988,220000000,United States of America
2,135397,Jurassic World,Action|Adventure|Science Fiction|Thriller,2015.0,1670400637,150000000,United States of America
3,168259,Furious 7,Action,2015.0,1506249360,190000000,Japan
4,99861,Avengers: Age of Ultron,Action|Adventure|Science Fiction,2015.0,1402805868,280000000,United States of America
5,109445,Frozen,Animation|Adventure|Family,2013.0,1274219009,150000000,United States of America
6,68721,Iron Man 3,Action|Adventure|Science Fiction,2013.0,1215439994,200000000,China
7,211672,Minions,Family|Animation|Adventure|Comedy,2015.0,1159398397,74000000,United States of America
8,271110,Captain America: Civil War,Adventure|Action|Science Fiction,2016.0,1153296293,250000000,United States of America
9,38356,Transformers: Dark of the Moon,Action|Science Fiction|Adventure,2011.0,1123794079,195000000,United States of America

In [55]:
movieDF.to_csv(path +'/updboxoffice.csv', encoding='utf-8', index=False)
newDF = pd.read_csv(path +'/'+ 'updboxoffice.csv')
newDF.shape#our file csv

(1246, 7)

In [57]:
newDF.loc[newDF['title'] == 'Deadfall']#Verify value

,id,title,genres,release_date,revenue,budget,country
1224,97614,Deadfall,Crime|Drama|Thriller,2012.0,66351,12000000,France

In [33]:
# load the oscar movies
oscarDF = pd.read_csv(path +'/'+ 'Oscars.csv',sep = ';')
oscarDF

,year,title,Budget,Genre,Spectateurs,Box Office
0,2019,Green Book,23'000'000,Drama|Comedy,No,Yes
1,2018,The Shape of Water,19'500'000,Drama|Fantasy|Romance,Yes,Yes
2,2017,Moonlight,4'000'000,Drama,Yes,Yes
3,2016,Spotlight,20'000'000,Drama|Thriller|History,Yes,Yes
4,2015,Birdman,18'000'000,Drama|Comedy,Yes,Yes
5,2014,Twelve Years a Slave,20'000'000,Drama|History,Yes,Yes
6,2013,Argo,44'500'000,Drama|Thriller,Yes,Yes
7,2012,The Artist,15'000'000,Drama|Comedy|Romance,Yes,Yes
8,2011,The King's Speech,15'000'000,Drama|History,Yes,Yes
9,2010,The Hurt Locker,15'000'000,Drama|Thriller|War,Yes,Yes

In [35]:
# load the oscar movies
palmeDF = pd.read_csv(path +'/'+ 'palmeDor.csv',sep = ';',engine='python',encoding='ISO-8859-1')
palmeDF

,Anne,Titre,Ralisateur,Budget,Gain,Vue,Rcipiendaires,Pays
0,2009,Le Ruban blanc,NaN,NaN,NaN,NaN,Michael Haneke,Autriche
1,2010,"Oncle Boonmee, celui qui se souvient de ses vi...",NaN,NaN,NaN,NaN,Apichatpong Weerasethakul,Thalande
2,2011,The Tree of Life,NaN,NaN,NaN,NaN,Terrence Malick,États-Unis
3,2012,Amour,NaN,NaN,NaN,NaN,Michael Haneke,Autriche
4,2013,La Vie d'Adle,NaN,NaN,NaN,NaN,Abdellatif Kechiche,France
5,2014,Winter Sleep,NaN,NaN,NaN,NaN,Nuri Bilge Ceylan,Turquie
6,2015,Dheepan,NaN,NaN,NaN,NaN,Jacques Audiard,France
7,2016,"Moi, Daniel Blake",NaN,NaN,NaN,NaN,Ken Loach,Royaume-Uni
8,2017,The Square,Ruben Östlund,"5,5 M Euros",NaN,339172,Ruben Östlund,Sude
9,2018,Une affaire de famille,Hirokazu Kore-eda,NaN,NaN,NaN,Hirokazu Kore-eda,Japon
10,2018,Le Livre d'image (« Palme d'or spéciale »),Jean-Luc Godard,NaN,NaN,728 905,Jean-Luc Godard,Suisse
11,2019,Parasite,Bong Joon-ho,"11,8 millions $",104 600 000 $,1 675 878,Bong Joon-ho,Corée du Sud